### ISSUE TITLE
MissingPluginException(No implementation found for method getProperties on channel flutter_user_agent)

### ISSUE THREAD

**Issue by jeansebastienZ** [j0j00/flutter_user_agent#15]
Hello,
Can't use the plugin , error coming out :

```
Error: MissingPluginException(No implementation found for method getProperties on channel flutter_user_agent)
    at Object.throw_ [as throw] (http://localhost:50439/dart_sdk.js:4351:11)
    at MethodChannel._invokeMethod (http://localhost:50439/packages/flutter/src/services/system_channels.dart.lib.js:943:21)
    at _invokeMethod.next (<anonymous>)
    at http://localhost:50439/dart_sdk.js:37968:33
    at _RootZone.runUnary (http://localhost:50439/dart_sdk.js:37822:58)
    at _FutureListener.thenAwait.handleValue (http://localhost:50439/dart_sdk.js:32783:29)
    at handleValueCallback (http://localhost:50439/dart_sdk.js:33331:49)
    at Function._propagateToListeners (http://localhost:50439/dart_sdk.js:33369:17)
    at _Future.new.[_completeWithValue] (http://localhost:50439/dart_sdk.js:33211:23)
    at async._AsyncCallbackEntry.new.callback (http://localhost:50439/dart_sdk.js:33234:35)
    at Object._microtaskLoop (http://localhost:50439/dart_sdk.js:38083:13)
    at _startMicrotaskLoop (http://localhost:50439/dart_sdk.js:38089:13)
    at http://localhost:50439/dart_sdk.js:33586:9
```

**Comment by ehsanbigzad** [comment]
> Hello,
> Can't use the plugin , error coming out :
> 
> ```
> Error: MissingPluginException(No implementation found for method getProperties on channel flutter_user_agent)
>     at Object.throw_ [as throw] (http://localhost:50439/dart_sdk.js:4351:11)
>     at MethodChannel._invokeMethod (http://localhost:50439/packages/flutter/src/services/system_channels.dart.lib.js:943:21)
>     at _invokeMethod.next (<anonymous>)
>     at http://localhost:50439/dart_sdk.js:37968:33
>     at _RootZone.runUnary (http://localhost:50439/dart_sdk.js:37822:58)
>     at _FutureListener.thenAwait.handleValue (http://localhost:50439/dart_sdk.js:32783:29)
>     at handleValueCallback (http://localhost:50439/dart_sdk.js:33331:49)
>     at Function._propagateToListeners (http://localhost:50439/dart_sdk.js:33369:17)
>     at _Future.new.[_completeWithValue] (http://localhost:50439/dart_sdk.js:33211:23)
>     at async._AsyncCallbackEntry.new.callback (http://localhost:50439/dart_sdk.js:33234:35)
>     at Object._microtaskLoop (http://localhost:50439/dart_sdk.js:38083:13)
>     at _startMicrotaskLoop (http://localhost:50439/dart_sdk.js:38089:13)
>     at http://localhost:50439/dart_sdk.js:33586:9
> ```

Relaunch the app, it will be solved.

**Comment by j0j00** [comment]
This library only works with Android and iOS, the stack trace appears to be running on a local browser.
