### ISSUE TITLE
!! example not working!!

### ISSUE THREAD

**Issue by minr** [j0j00/flutter_user_agent#7]
Error LOG:

```log
E/flutter ( 9549): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: MissingPluginException(No implementation found for method getProperties on channel flutter_user_agent)
E/flutter ( 9549): #0      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:319:7)
E/flutter ( 9549): <asynchronous suspension>
E/flutter ( 9549): #1      FlutterUserAgent.init (package:flutter_user_agent/flutter_user_agent.dart:19:43)
E/flutter ( 9549): #2      FlutterUserAgent.getPropertyAsync (package:flutter_user_agent/flutter_user_agent.dart:46:11)
```

Flutter version:

```shell
[✓] Flutter (Channel stable, v1.12.13+hotfix.5, on Mac OS X 10.15.2 19C57,
    locale zh-Hans-CN)
    • Flutter version 1.12.13+hotfix.5 at /Users/min/flutter
    • Framework revision 27321ebbad (3 days ago), 2019-12-10 18:15:01 -0800
    • Engine revision 2994f7e1e6
    • Dart version 2.7.0
```

**Comment by j0j00** [comment]
I can't replicate this issue. You should try cleaning your project and rebuilding from scratch.

Or trying to debug the crash yourself, isolating what is causing it and potentially proposing a fix.
